name: samplelocalproject
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  mobx_codegen: ^2.0.4
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  kartal: ^2.2.0
  lottie: ^1.2.1
  build_runner: ^2.1.5
  hive_flutter: ^1.1.0
  google_fonts: null
  
  flutter_localizations:
        sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.0
  flutter_slidable: ^1.1.0



flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/lottie/
        - assets/lang/
        - assets/fonts/
